"use client";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
 import Footer from "./_components/Footer";
import Scrollup from './scrollup/Scrollup';

 import { Provider } from "react-redux";
import store from "./_redux/store";
import Head from 'next/head';
import React,{useState,useEffect} from 'react'
import { Toaster } from 'react-hot-toast';

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignOutButton,
  UserButton,
} from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";

const inter = Roboto({ subsets: ["latin"], weight: "700" });

 const metadata= {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [cartt, setcartt] = useState([]);

  return (
    <ClerkProvider>
      <Provider store={store}>
      <html lang="en">
      <Head>
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description} />
      </Head>
        <body className={inter.className} suppressHydrationWarning={true}>
  <Toaster position="top-right"/>
          <Header />
          {children}
          <Footer/> 
          <Scrollup/>
        </body>
      </html>
      </Provider>
    </ClerkProvider>
  );
}
